### ISSUE TITLE
PDE verification build fails with java.lang.NoClassDefFoundError: org/eclipse/jgit/internal/JGitText

### ISSUE THREAD

**Issue by vogella** [eclipse-pde/eclipse.pde#1020]
See https://github.com/eclipse-pde/eclipse.pde/actions/runs/7263610468/job/19789307909?pr=871 this seems to happen regulary but not always:

Error:  After correcting the problems, you can resume the build with the command
Error:    mvn <args> -rf :org.eclipse.pde.ui.tests
Error: Exception in thread "Thread-3" java.lang.NoClassDefFoundError: org/eclipse/jgit/internal/JGitText
	at org.eclipse.jgit.internal.util.ShutdownHook.cleanup(ShutdownHook.java:85)
	at java.base/java.lang.Thread.run(Thread.java:840)
Caused by: java.lang.ClassNotFoundException: org.eclipse.jgit.internal.JGitText

**Comment by laeubi** [comment]
This seems to be a bad `ShutdownHook` that is executed when the bundle classlaoder is already disposed here

```
	private void cleanup() {
		shutdownInProgress = true;
		ExecutorService runner = Executors.newWorkStealingPool();
		try {
			runner.submit(() -> {
				this.doCleanup();
				return null;
			}).get(30L, TimeUnit.SECONDS);
		} catch (RejectedExecutionException | InterruptedException
				| ExecutionException | TimeoutException e) {
			LOG.error(JGitText.get().shutdownCleanupFailed, e);
		}
		runner.shutdownNow();
	
}```

the problem is that the hook is always registered even if the bundle is stopped, that is most likely wrong, I don't see how a shutdown hook of that kind makes any sense inside an OSGi framework, JGit should check if it is running in an OSGi framework and then use a `BundleListener` or similar instead, there is nothing PDE can do here so please report that to jgit, once this is fixed and released tycho can be updated and the error will go away.
