### ISSUE TITLE
Baseline not bound - there are no installed VMs compatible with the required execution environments

### ISSUE THREAD

**Issue by fipro78** [eclipse-pde/eclipse.pde#1327]
Since the last few versions I get the following error when trying to set the API baseline for NatTable:

_Baseline not bound - there are no installed VMs compatible with the required execution environments_

<img width="429" alt="image" src="https://github.com/eclipse-pde/eclipse.pde/assets/3041955/3a3d64a2-7374-4695-8ce6-beb59b08ace6">

I have a VM connected to every LTS Java version (8, 11, 17, 21). I was compatible with Java 8 for a long time, and now I am trying to update to Java 11. But I can't use the API tooling anymore.

Any hint what could be the issue? Are bundles missing in the baseline?

**Comment by iloveeclipse** [comment]
Could you please provide steps to reproduce? Which JVM is configured in the IDE, which target platform, which Eclipse version, which was working?

**Comment by merks** [comment]
Note that the Oomph setup populates a baseline from your update site...

With the 2024-06 committers IDE I see these problems:

![image](https://github.com/eclipse-pde/eclipse.pde/assets/208716/d045fcaf-53ab-4fce-80aa-d5b873522df9)

But with the latest Platform SDK IDE, the problem is gone:

![image](https://github.com/eclipse-pde/eclipse.pde/assets/208716/c17b6f2b-72c0-4486-8645-73d7a6e091ae)

Have you tried with the 4.33 SDK?  Because this also works for me with the latter:

![image](https://github.com/eclipse-pde/eclipse.pde/assets/208716/31956cc0-d056-4c95-a4c7-0cc93d005913)

But not with the older installation:

![image](https://github.com/eclipse-pde/eclipse.pde/assets/208716/23e23d30-2d72-4f85-811b-e7999d081578)

I think this is the problem @HannesWell a short while ago.

**Comment by fipro78** [comment]
Eclipse:
Version: 2024-06 (4.32.0)
Build id: 20240606-1231

JVM:
The JVM delivered with the Eclipse IDE
_plugins/org.eclipse.justj.openjdk.hotspot.jre.full.win32.x86_64_21.0.3.v20240426-1530/jre/bin\server\jvm.dll_

- Checkout the NatTable project: https://github.com/eclipse-nattable/nattable
- Activate the project target platform in the _target-platform_ project
- Set the API baseline  
Open the workspace preferences (Window > Preferences) and head to Plug-in Development > API Baselines. There, hit _Add Baseline..._ to define a new baseline. Choose any name you like (the version of the release the baseline represents might be suitable, i.e. NatTable 2.4.0). Then, press _Browse..._ and choose the _api-baseline_ folder within the NatTable git repository.

I went back to 2022-09 and the issue always occurs. Which is strange, because I am sure I used that approach for years now. :(

@merks
Thanks for the pointer. I have seen that you create a baseline with the Oomph setup, and that this one works. But as I am still working on cleaning up after your changes (just to make them consistent, not that your changes need to be cleaned up ;) ), I have my old setup and do not use the Oomph yet.

I have tried 4.33 M1 where the issue still exists. Then I tried the latest 4.33 I-Build, and the issue is gone. So it seems to be fixed quite recently.

**Comment by merks** [comment]
See pictures that I tried what you do too.  Pointing at the folder.

**Comment by fipro78** [comment]
I have seen that and can confirm that it works with the latest 4.33 I-Build. :)

**Comment by merks** [comment]
Very good.  Then it sounds like it didn’t make m1. Too bad.  FYI. I think as of the 2024-06 release you should be able to update from a platform I-build to get the fix into your ide sooner.

**Comment by HannesWell** [comment]
> I think this is the problem @HannesWell a short while ago.

Yes this sounds like a duplicate of https://github.com/eclipse-pde/eclipse.pde/issues/1301.

I'm glad this is fixed already. :)
