### ISSUE TITLE
2 ApiFilterStoreTests fail since I20240722-0320 on two platforms

### ISSUE THREAD

**Issue by iloveeclipse** [eclipse-pde/eclipse.pde#1348]
See

- https://download.eclipse.org/eclipse/downloads/drops4/I20240722-0320/testresults/html/org.eclipse.pde.api.tools.tests_ep433I-unit-macM1-java17_macosx.cocoa.aarch64_17.html
- https://download.eclipse.org/eclipse/downloads/drops4/I20240722-0320/testresults/html/org.eclipse.pde.api.tools.tests_ep433I-unit-win32-java17_win32.win32.x86_64_17.html

Possible candidates (new in the `I20240722-0320` tag in PDE)
- https://github.com/eclipse-pde/eclipse.pde/pull/1345
- https://github.com/eclipse-pde/eclipse.pde/pull/1347
- https://github.com/eclipse-pde/eclipse.pde/pull/1344
- https://github.com/eclipse-pde/eclipse.pde/pull/1343

@HannesWell : could you please check?

**Comment by HannesWell** [comment]
> @HannesWell : could you please check?

Yes I can do that, but since I don't see a direct reason how these changes are related to the failures and since, if I recall correctly, have already seen such failures happen occasionally I hope this is just a hick-up that vanishes in the next I-builds. The latest builds were also green and locally these tests pass too.

**Comment by HannesWell** [comment]
In the latest I-build these tests have passed again:
https://download.eclipse.org/eclipse/downloads/drops4/I20240722-1800/testResults.php

I assume that was just a temporary hick-up. But if we want to avoid that in the future (which would be good, if it happens more often), I'm not sure if anything about this can be done in PDE.
