### ISSUE TITLE
This is very import info,about ui

### ISSUE THREAD

**Issue by d131412** [eclipse-pde/eclipse.pde#1506]
After my system was updated to Windows 11, version 24H2, the black theme of the official version 4.33 of Eclipse 2024-09 became invalid. The gray scroll bar and the black theme of the menu bar have both become invalid and turned white, and the colors cannot be changed.

-- Configuration Details --

Product: Eclipse IDE 4.33.0.20240905-0613 (org.eclipse.epp.package.jee.product)Installed Features:

 org.eclipse.pde 3.16.0.v20240903-0240
![20241204232551](https://github.com/user-attachments/assets/590feef5-985e-43b0-b41a-b7700e80067f)
![20241204232707](https://github.com/user-attachments/assets/1c637fea-067c-43a9-9ee8-eb261f192afa)
![20241204232815](https://github.com/user-attachments/assets/579454e7-229b-4329-9464-27e21f66cd50)

**Comment by d131412** [comment]
![20241204233704](https://github.com/user-attachments/assets/de34bd0a-c351-40ce-bb7c-b8d75e45168d)

**Comment by d131412** [comment]
![20241204235827](https://github.com/user-attachments/assets/e9bcb0ac-fe6f-44ac-b096-f6a4d0cd40f1)

**Comment by HannesWell** [comment]
Thanks for your report. 
Please update your Eclipse installation to the latest version 2024-12, which was released today.
 If this issue is still present, then please report it to
https://github.com/eclipse-platform/eclipse.platform.ui.
PDE is unfortunately not the right place for that kind of issue.
