### ISSUE TITLE
API tools gets mad when changing extension point and complains with strange error but only if implemented

### ISSUE THREAD

**Issue by laeubi** [eclipse-pde/eclipse.pde#378]
Here is an example where API tools getting completely confused:

- https://github.com/eclipse-pde/eclipse.pde/pull/214

the reason seems the change in the extension point schema:
https://github.com/eclipse-pde/eclipse.pde/pull/214/files#diff-1dd8fb28f1eb527546dd6cd20cdbbd319edc02dc1840a138799874a958c7edef

but the errors reported are completely wrecked. Even worse, if one removes the **implementation** of the extension point, API tools do **not** complain. Then when one implements the extension point the first time things go bad...

**Comment by HannesWell** [comment]
Another related PRs:
- https://github.com/eclipse-pde/eclipse.pde/pull/374
- https://github.com/eclipse-pde/eclipse.pde/pull/379

**Comment by merks** [comment]
This problem was self-inflicted by the very nature of the change being made.  In particular, when building the workspace baseline, the builder filters out source components:

```
SourceDefaultHandler.startElement(String, String, String, Attributes) line: 38	
SAXParserImpl$JAXPSAXParser(AbstractSAXParser).startElement(QName, XMLAttributes, Augmentations) line: 518	
XMLDocumentScannerImpl(XMLDocumentFragmentScannerImpl).scanStartElement() line: 1407	
XMLDocumentScannerImpl$ContentDriver(XMLDocumentFragmentScannerImpl$FragmentContentDriver).next() line: 2726	
XMLDocumentScannerImpl.next() line: 605	
XMLDocumentScannerImpl(XMLDocumentFragmentScannerImpl).scanDocument(boolean) line: 542	
XIncludeAwareParserConfiguration(XML11Configuration).parse(boolean) line: 889	
XIncludeAwareParserConfiguration(XML11Configuration).parse(XMLInputSource) line: 825	
SAXParserImpl$JAXPSAXParser(XMLParser).parse(XMLInputSource) line: 141	
SAXParserImpl$JAXPSAXParser(AbstractSAXParser).parse(InputSource) line: 1224	
SAXParserImpl$JAXPSAXParser.parse(InputSource) line: 637	
SAXParserImpl.parse(InputSource, DefaultHandler) line: 326	
BundleComponent.containsSourceExtensionPoint(String) line: 1104	
BundleComponent.isSourceComponent(Map<String,String>, File) line: 1060	
ProjectComponent(BundleComponent).isSourceComponent() line: 1043	
WorkspaceBaseline.addApiComponents(IApiComponent[]) line: 92	
ApiBaselineManager.createWorkspaceBaseline() line: 717	
ApiBaselineManager.getWorkspaceBaseline() line: 637	
ApiAnalysisBuilder.build(int, Map<String,String>, IProgressMonitor) line: 387	
BuildManager$2.run() line: 1020	
SafeRunner.run(ISafeRunnable) line: 45	
BuildManager.basicBuild(int, IncrementalProjectBuilder, Map<String,String>, MultiStatus, IProgressMonitor) line: 247	
BuildManager.basicBuild(IBuildConfiguration, int, IBuildContext, ICommand[], MultiStatus, IProgressMonitor) line: 303	
BuildManager$1.run() line: 392	
SafeRunner.run(ISafeRunnable) line: 45	
BuildManager.basicBuild(IBuildConfiguration, int, IBuildContext, MultiStatus, IProgressMonitor) line: 395	
BuildManager.basicBuildLoop(IBuildConfiguration[], IBuildConfiguration[], int, MultiStatus, IProgressMonitor, int, boolean) line: 506	
BuildManager.basicBuildLoop(IBuildConfiguration[], IBuildConfiguration[], int, MultiStatus, IProgressMonitor) line: 454	
BuildManager.build(IBuildConfiguration[], IBuildConfiguration[], int, IProgressMonitor) line: 536	
AutoBuildJob.doBuild(IProgressMonitor) line: 161	
AutoBuildJob.run(IProgressMonitor) line: 255	
Worker.run() line: 63	
```

That's done by the test in this class which looks for `org.eclipse.pde.core.source` extension points:

https://github.com/eclipse-pde/eclipse.pde/blob/6249405a278ccef2b2f02fe21869c9517b121208/apitools/org.eclipse.pde.api.tools/src/org/eclipse/pde/api/tools/internal/util/SourceDefaultHandler.java#L22-L44

Therefore, because this was added to the `org.eclipse.pde.core` plugin.xml
```
    </extension>
        <extension
          point="org.eclipse.pde.core.source">
          <locator class="org.eclipse.pde.internal.core.ColocationPluginSourcePathLocator" />
          <locator class="org.eclipse.pde.internal.core.LocalMavenPluginSourcePathLocator" />
    </extension> 
```
that bundle was determined to be a source bundle and was removed from the set of workspace API components.  As a result, no API checking was done on `org.eclipse.pde.core` and when analyzing the re-exports of  `org.eclipse.pde.ui`, it determined that no API component provided these classes/packages and therefore `org.eclipse.pde.ui` no longer exported them in the latest version.

I would be possible to make the test fancier/smarter and look for an actual `location` element versus the new `locator` element to address this problem.  But given that the design has been changed to avoid overloading the use of the `org.eclipse.pde.core.source` extension point, there seems no point in trying to fix this at all.  

That was a few hours well ~~wasted~~ spent...

**Comment by laeubi** [comment]
So every bundle implementing `org.eclipse.pde.core.source` is ignored by API tools? That's really strange...

**Comment by merks** [comment]
Apparently that is an old crappy way to do it that's been replaced by an entry in the MANIFEST.MF:

https://github.com/eclipse-pde/eclipse.pde/blob/6249405a278ccef2b2f02fe21869c9517b121208/apitools/org.eclipse.pde.api.tools/src/org/eclipse/pde/api/tools/internal/model/BundleComponent.java#L1046-L1074
