### ISSUE TITLE
Target platform shows available entries as meta-info, would be more interesting how many entries have been selected

### ISSUE THREAD

**Issue by vogella** [eclipse-pde/eclipse.pde#857]
I see that the 2023-09 release has 557 plug-ins available as meta-info in the target editor.

![image](https://github.com/eclipse-pde/eclipse.pde/assets/139910/ea373cde-4614-463c-888f-d7f001c8e8d2)

I think it would be more interesting how many entries I have selected, maybe we could change the information to 

"3 out of 557 entries selected" or something similar.

**Comment by laeubi** [comment]
> I think it would be more interesting how many entries I have selected

In what regard? e.g. if you tick the "show location content" you will see the 557 plugins mentioned, so if changed this must be possibly sensitive to that setting.

> how many entries I have selected

Also one should keep in mind that the UI only allows to select "root" IUs but in the source you can select also other IUs so this could result in more "seleted" than visible to the user from UI.

> "3 out of 557 entries selected" or something similar.

Pleas be aware that 557 is not the total number of items you can select, it is the number of bundles  that got resolved due to your selection!

**Comment by vogella** [comment]
Make sense, thanks @laeubi for the explanation.
