### ISSUE TITLE
javax.inject with Build id: I20231107-0600 cannot be found even though target platform is 2023-09

### ISSUE THREAD

**Issue by vogella** [eclipse-pde/eclipse.pde#902]
With Eclipse SDK
Version: 2023-12 (4.30)
Build id: I20231107-0600
OS: Linux, v.6.2.0-36-generic, x86_64 / gtk 3.24.37
Java vendor: Eclipse Adoptium
Java runtime version: 21+35-LTS
Java version: 21

java.lang.Error: Unresolved compilation problems: 
	The import javax.inject cannot be resolved
	The import javax.inject cannot be resolved

Repo to reproduce: git@github.com:vogellacompany/codeexamples-ide.git Open the target-platform.target file and activate

It sometimes works but after a restart of the IDE is fails.

@HannesWell I guess that is related to the javax.inject replacement. I would IMHO really bad if someone who is using a target platform pointing to an older release still cannot use javax.inject

**Comment by vogella** [comment]
Update: If I switch my runtime JRE to Java 17  javax.inject is found again.

**Comment by HannesWell** [comment]
> @HannesWell I guess that is related to the javax.inject replacement. I would IMHO really bad if someone who is using a target platform pointing to an older release still cannot use javax.inject

I agree that this would be bad.
However the javax.inject providing bundle is not part of the SDK anymore, but of course it still works to have it in the TP. It is just an ordinary bundle providing annotation and there is no special support for it from a PDE point of view.
Maybe it is just a problem while resolving your TP? Can you check if the Target-Platform State view shows it and if the Plugin-Dependencies Container contains the corresponding jar?

**Comment by merks** [comment]
Note is that many people are quite used to just using the running IDE as their target platform, and now gradually the Eclipse SDK is less and less an SDK that can be used in such a way.   Even when using a *.target, It's likely that quite a few people will now need to add this explicitly to their target whereas formerly the planner mode could have included it implicitly...

**Comment by vogella** [comment]
Something is fishy here. Started again new, this time directly with Java 17.


![image](https://github.com/eclipse-pde/eclipse.pde/assets/139910/bd79b2fd-fd64-41ca-ace4-9b9cdb13194b)


Target platform:

```
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<?pde version="3.8"?>
<target name="target-platform">
 <locations>
  <location includeAllPlatforms="false" includeConfigurePhase="true" includeMode="slicer" includeSource="true" type="InstallableUnit">
   <repository location="https://download.eclipse.org/releases/2023-09"/>
   <unit id="org.eclipse.equinox.sdk.feature.group" version="0.0.0"/>
   <unit id="org.eclipse.platform.sdk" version="0.0.0"/>
   <unit id="org.eclipse.pde.spies.feature.group" version="0.0.0"/>
  </location>
 </locations>
</target>
```


![image](https://github.com/eclipse-pde/eclipse.pde/assets/139910/a6ef4c9b-248a-4e73-b102-811a4e5a4e7f)

After three times, re-loading the target platform and clean all projects, it now compiles. So not sure what triggers this and what is the right rix.

For me, not a big thing, I will migrate my training to 2023-12 as soon as it is out but if that "instability" hits RCP clients, they will not be able to use 2023-12 (I get this temporary error now three days in a row after rebooting).

**Comment by vogella** [comment]
If I use "slicer" mode, it finds it in the target platform but still is not able to compile.

```
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<?pde version="3.8"?>
<target name="target-platform">
 <locations>
  <location includeAllPlatforms="false" includeConfigurePhase="true" includeMode="planner" includeSource="true" type="InstallableUnit">
   <repository location="https://download.eclipse.org/releases/2023-09"/>
   <unit id="org.eclipse.equinox.sdk.feature.group" version="0.0.0"/>
   <unit id="org.eclipse.platform.sdk" version="0.0.0"/>
   <unit id="org.eclipse.pde.spies.feature.group" version="0.0.0"/>
  </location>
 </locations>
</target>
```

![image](https://github.com/eclipse-pde/eclipse.pde/assets/139910/12e51318-a7cc-48f8-b025-5d173e99f5e2)

**Comment by vogella** [comment]
If that is what will happen on other developer machines, 2023-12 will not be usable for plug-in develop if javax.inject is still used. And if IDE plug-ins want to to support more than the latest release, they have to use the old inject.

@HannesWell or @merks in case you find this important enough, clone https://github.com/vogellacompany/codeexamples-ide and import all projects, activate the the https://github.com/vogellacompany/codeexamples-ide/blob/master/target-platform/target-platform.target file.

Here is what I do then to get the error:

1.) Leaving target file open in the editor and have the editor has focus
2.) Shutdown Eclipse
3.) Reboot (might not be necessary)
4.) Start machine again
5.) Start Eclipse via the command line with Java 17
6.) Wait until the target file resolves (it is open and someone thought that having this file open should trigger the download of the JAR files again (this was discussed in another issue a while ago)
7.) See the compiler errors (at least in my case)

**Comment by merks** [comment]
@vogella 

As I vaguely suggested, you need to explicitly add a bundle exporting the javax.inject package to the target platform.  It has a rather unwieldy (and surprising) name:

![image](https://github.com/eclipse-pde/eclipse.pde/assets/208716/d7047925-e012-42d3-8f18-d1b3baf21232)

Also because there are two versions of it, and because you need the 1.x version, you have to specify the version exactly too.

**Comment by vogella** [comment]
@merks which I would understand if this would not work after a few reloads and clean build. And this setup worked without any change in 2023-09 IDE (target still points to 2023-12) so this is definitely a regression/ change

**Comment by merks** [comment]
I guess I read too much into the title about the TP being **2023-12**:

> javax.inject with Build id: I20231107-0600 cannot be found even though target platform is **2023-12**

That PDE's resolving of the target platform is often kind of flaky doesn't surprise me.  I used to almost panic when I accidentally opened the target editor, because it was so often the case that "bad things happen".    There seems to be no good separation between what the editor is doing when it decides its a good time to resolve and the actual target platform currently being used by the IDE to compile all the projects.  But that's a digression...

I suppose your TP is kind of a mixed bag:
```
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<?pde version="3.8"?>
<target name="target-platform">
    <locations>
        <location includeAllPlatforms="false" includeConfigurePhase="true" includeMode="planner" includeSource="true" type="InstallableUnit">
            <repository location="http://download.eclipse.org/releases/2023-09"/>
            <unit id="org.eclipse.equinox.sdk.feature.group" version="0.0.0"/>
            <unit id="org.eclipse.platform.sdk" version="0.0.0"/>
        </location>
	
		
		<location includeAllPlatforms="false" includeConfigurePhase="true" includeMode="planner" includeSource="true" type="InstallableUnit">
            <repository location="https://download.eclipse.org/releases/latest"/>
                 <unit id="org.eclipse.pde.spies.feature.group" version="0.0.0"/>
        </location>
        
    </locations>
</target>
```
With some latest and some older.  That just seems to be inviting for trouble where you might get some very strange mixture of old and new content, maybe with duplicate versions...

**Comment by merks** [comment]
Actually, with the way planner is implemented I think it will resolve all these units against all (both) the repositories so mostly you will get latest (4.30) units, which is the problem I described.   I have no idea about cleaning and rebooting and have no time for that.  Sorry.

**Comment by merks** [comment]
I see, and latest is 2023-09.  Not sure the reason for the two different URLs...

**Comment by merks** [comment]
In a debug launch  IDE,  the target:

![image](https://github.com/eclipse-pde/eclipse.pde/assets/208716/ef1b6ad0-b51a-4061-9b4c-cc600dfc20f6)

appears to resolve correctly to include javax.inject:

![image](https://github.com/eclipse-pde/eclipse.pde/assets/208716/8421cca0-7802-4950-b292-6c4b487b12ac)

**Comment by vogella** [comment]
@merks yes, it does this "sometimes" but not after a restart of the IDE with my above steps. To summarize:

1.) It worked with IDE 2023-09
2.) If worked in the dev cycle before we replaced javax.inject with the new package name (which I think is super work from @HannesWell and I'm very impressed that Hannes managed to implement this).
3.) It works "sometimes" in IDE 2023-12
4.) It reliable does NOT work for me every morning and requires approx. 10 minutes to make the working target to resolve and compile

I just wanted to point out that if this problem hits the RCP and plug-in dev space, 2023-12 will not be usable for the larger  plug-in community. Big IF, maybe other target platforms may reveal this issue.
 
> There seems to be no good separation between what the editor is doing when it decides its a good time to resolve and the actual target platform currently being used by the IDE to compile all the projects.

I hugely dislike that the target editor resolves automatically. My recommendation to clients is to: "never leave the target editor open after you have activated it, otherwise it resolves every time you accidentally switch to the editor." Horrible design IMHO, but the last time I tried to remove this "useful feature" a few others pointed out how useful this is and I lost the energy over the years to fight against such opinions.

**Comment by vogella** [comment]
> I see, and latest is 2023-09. Not sure the reason for the two different URLs...

If you combine it, the faulty behavior is the same.

**Comment by HannesWell** [comment]
> Note is that many people are quite used to just using the running IDE as their target platform, and now gradually the Eclipse SDK is less and less an SDK that can be used in such a way. Even when using a *.target, It's likely that quite a few people will now need to add this explicitly to their target whereas formerly the planner mode could have included it implicitly...

That's right and I agree that this is a drawback, but in order to avoid this, we would have to add these bundle explicitly e.g. to the `org.eclipse.sdk` feature. Or would need a plugin that imports/requires the javax-providing bundles.
And I think this would be sub-optimal too, since the same problem would aries when we eventually remove this again.

But I have drafted an update to the N&N entry that explicitly mentions the potential need to add it to the TP:
- https://github.com/eclipse-platform/www.eclipse.org-eclipse/pull/85

This also mentions strategies to extend the compatibility with past, current and future versions of the injector, that **probably** work.
I haven't tried your steps to reproduce yet (will try to do that tomorrow), but what I have noticed is that the SimRel repo does not provide the 'new' `javax.inject/annotation` providing bundles with name `jakarta.inject.jakarta.inject-api` and  `jakarta.annotation-api` in the 1.x versions that provide the annotations in the javax namespace, but only the 'old' Orbit variants (those named `javax.inject/annotation` and a qualifier in the version):
https://download.eclipse.org/releases/2023-12/202310271000/plugins/

I assume this is because somebody includes those Plugins in their features or requires the bundle instead of importing them?

It also does not provide the sources of `jakarta.inject.jakarta.inject-api` and  `jakarta.annotation-api` in version 2.
Maybe the SimRel repo should be changed to include as many sources as possible and not only those included in features?

**Comment by merks** [comment]
The aggregator does automatically add source if they are available, so if there is no source for something I believe it's because it isn't available in any repository.  The Orbit repository itself is deliberately not added to the aggregation because then people will rely on that and then when Orbit provides a newer version to replace an older version, the aggregation is broken leaving Orbit unable to replace an old version with a new version. 

But now that I check, I see that the flag to do that is set to false:

https://github.com/eclipse-simrel/simrel.build/pull/48

**Comment by merks** [comment]
It's there now:

![image](https://github.com/eclipse-pde/eclipse.pde/assets/208716/e63099e8-ae12-4f34-88a2-df6454c4b842)

I've provided jakarta.* bundles exporting javax.* namespaces for all the javax.*bundles so these two are available:

![image](https://github.com/eclipse-pde/eclipse.pde/assets/208716/eda64b8d-5f6e-4d05-982f-8972e38d8499)

The javax.inject bundles are not provided:

![image](https://github.com/eclipse-pde/eclipse.pde/assets/208716/437bcf86-5ac0-4449-87a2-32b8dd10e62d)

But getting the SimRel folks to do new builds that use the latest things is challenging at best...

**Comment by HannesWell** [comment]
> But now that I check, I see that the flag to do that is set to false:\n\neclipse-simrel/simrel.build#48

Pefect, thanks!

And yes the Eclipse-sdk repo definitivly provides the annotation bundeles from both namespaces and with sources.

> I've provided jakarta.* bundles exporting javax.* namespaces for all the javax.*bundles so these two are available:

Great, I also was about to provide an update of the SDK contribution.

> The javax.inject bundles are not provided:\n\n\n\nBut getting the SimRel folks to do new builds that use the latest things is challenging at best...

Sadly yes. :/

**Comment by HannesWell** [comment]
@vogella I tried out your example in a fresh workspace and for me PDE worked as expected and I had no issues regarding javax (which I would not be able to explain at the moment since the changes done in the SDK should not cause compilation errors in developed plugins).
But I noticed a few things that could cause your current problems respectively will be problems in the future.
- Your Plugin `com.vogella.ide.first` requires the bundle `javax.inject` which is bad, since it will hopefully be soon (maybe already in 23-12) be gone and will be replaced by the 'official' `jakarta.inject.jakarta.inject-api` `1.0.5`. It is not in the 23-12 M2 repo but will be there in M3. You should use Import-Package for that Plugin as well.
- The Plugin `org.eclipse.platform.sdk` seems to be gone in 23-12.
- You will probably have to add a unit like `<unit id="jakarta.inject.jakarta.inject-api" version="1.0.5"/>` to your TP as soon as M3 is published for the SimRel since no Plugin in the SDK should require `javax.inject` anymore.

**Comment by vogella** [comment]
Thanks Hannes, the `com.vogella.ide.first` for plug-in to package dependencies has been applied. As for the rest I plan to update the example code to jakarta.inject once 2023-12 is out.

Good news is, is that the failure is not reproduceable by me anymore, so my issue might have only been a temporary issue. Thanks @HannesWell and @merks for the comments.
