### ISSUE TITLE
Workspace Product Export does not respect 'Eclipse-BundleShape: dir' Manifest-Header anymore

### ISSUE THREAD

**Issue by HannesWell** [eclipse-pde/eclipse.pde#995]
When exporting a product from the workspace using PDE's product export the `Eclipse-BundleShape: dir` Manifest headers are not considered and plug-ins containing it are therefore not extracted.

To replicate just import the following simple product definition and export the `my.product`:
[my.example.product.zip](https://github.com/eclipse-pde/eclipse.pde/files/13614567/my.example.product.zip)

This has the consequence that the exported product cannot even be launched since for example `org.eclipse.equinox.launcher.*` is not extracted and the launcher cannot find its companion shared library.
Thus this is a sever regression for those that use the product export (like us), probably from
- https://github.com/eclipse-pde/eclipse.pde/pull/770
or its follow-up
 - https://github.com/eclipse-pde/eclipse.pde/pull/886

I can take core of this later (probably at the weekend).

**Comment by Rainer7000** [comment]
Is there any progress with this bug, or is it paused until   https://github.com/eclipse-pde/eclipse.pde/issues/862  is resolved ?
I'm asking because after 2023-09 and 2023-12 this is the third time in a row that we are unable to update to the current version of eclipse because of a unresolved but already known bug. In this case the short term solution could be rather trivial (directory-unpack-flag gets ignored somewhere) and the complete rework of the PDE Export Wizard could lead to a very long development phase where the export-functionality is still broken in the eclipse-distribution.

**Comment by laeubi** [comment]
If this is crucial to your business and likes to speed up the development you can [contact me](https://xn--lubisoft-0za.gmbh/en/#opensource) to enter a contract about this specific issue or if you need dedicated enterprise support.

Of course a PR to fix the problem would also be welcome as it seems you have developers at hand that are familiar with Eclipse RCP, see the [contribution guides here](https://github.com/eclipse-platform/.github/blob/main/CONTRIBUTING.md) and if Eclipse is an important Technology for you you maybe even want to join the [Eclipse IDE Workingroup](https://www.eclipse.org/membership/#tab-membership) that also regularly funds development in critical areas or [consider a sponsoring](https://www.eclipse.org/sponsor/ide/) to improve Eclipse IDE in general.

**Comment by Rainer7000** [comment]
Unfortunately we are a rather small company and I'm the only Java-Developer, so our resources are very limited.
Although we decided to dedicate 100% of our java-developer-resources to the issue for quite sime time ;)
I could make out one of the commits that removed the unpack attribute from plugin-builds:
    commit 824f124d0ac968f14aced1398881e7274798fd28
    Author: Alshama M S <ALSHAMA.M.S@ibm.com> 2023-09-27 07:27:36
I have tried to reverse some of the changes but only could make it work for a simple test-product consisting of plugins.
When I tried to build our more complex feature-based product the changes had no effect. 
It seems the feature to plugin resolution is done in a seperate process and the changed code isn't used for that.
Never the less I attach the patch that enabled the plugin-unpacking here for further refference.
[product_build_unpack.patch](https://github.com/eclipse-pde/eclipse.pde/files/14848957/product_build_unpack.patch)

**Comment by fpapai** [comment]
hello,
We are in the same situation as Rainer700: 1 java developer, no resources/time to understand Eclipse internals to create a correct fix through a PR.

This bug breaks an important feature of Eclipse IDE: exporting plugins/applications.
Not sure why is not considered for a fix by Eclipse team for the next release.

**Comment by laeubi** [comment]
> Not sure why is not considered for a fix by Eclipse team for the next release.

Because there is no "Eclipse Team" that can fix issues for other companies (either large or small), see https://github.com/eclipse-pde/eclipse.pde/issues/995#issuecomment-2006896197

Still you can stay on older releases / toolchains if it works there for you but there is no grantee.

> This bug breaks an important feature of Eclipse IDE: exporting plugins/applications.

Just because it is important for you don't mean its important for the wider audience, e.g. most companies simply have a CI pipeline that produce the artifacts, because exporting from the IDE is risky and error prone so that defiantly not something important for them.

I also wanted to mention that of course it is sensible for a *group of affected users* to work together or fund a campaign to pay someone to work on that (again [feel free to contact me](https://xn--lubisoft-0za.gmbh/en/#opensource)) I already did this in the past with success, the spirit of Open Source Software does not end when you download the next release ...

**Comment by HannesWell** [comment]
This should now be fixed with https://github.com/eclipse-pde/eclipse.pde/pull/1271.
While working on this I noticed another potential problem in the export fixed in https://github.com/eclipse-pde/eclipse.pde/pull/1270.

@Rainer7000 and @fpapai please verify with tonight's I-build that this is really fixed. The link will probably be
https://download.eclipse.org/eclipse/downloads/drops4/I20240515-1800/

> We are in the same situation as Rainer700: 1 java developer, no resources/time to understand Eclipse internals to create a correct fix through a PR.
> 
> This bug breaks an important feature of Eclipse IDE: exporting plugins/applications. Not sure why is not considered for a fix by Eclipse team for the next release.

Out of curiosity and assuming you work for the company you named in your GH bio, I wonder why a tech company from the silicon-valley with over 2000 employers (according to Wikipedia) has only one Java developer?
It's also funny that a company with over half a billion of revenue relies on a guy at the other end of the world spending two hours of his free-time to fix that bug (after working day time in a small company too).
I don't want to start the open-source is exploited song, just wanted to shed some light on what or better who the 'Eclipse-team' is. And of course there are also other contributors with individual circumstances, if you are interested please read https://github.com/eclipse-platform/#community

I fixed that out of conscientiousness, but in that sense: Quality contributions are more welcome and the most reliable way to ensure that your needs are met. Besides that you can also learn a lot about Eclipse, which can be beneficial for you products based on Eclipse.

**Comment by Rainer7000** [comment]
I checked the I-Build, but unfortunately the issue is only 'half-fixed'.
The launcher plugin **org.eclipse.equinox.launcher.win32.win32.x86_64_1.2.1000.v20240507-1834** gets extracted in the build,
but a workspace-plugin which i tagged with **Eclipse-BundleShape: dir** gets exported as a jar.
I attach my test-project for analysis.
[TestAppRCPAndPlugin.zip](https://github.com/eclipse-pde/eclipse.pde/files/15331783/TestAppRCPAndPlugin.zip)
